/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import org.kordamp.ikonli.materialdesign2.MaterialDesignA;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author KAROL JOHN
 */
public class BackBtn extends javax.swing.JPanel {

    /**
     * Creates new form BackBtn
     */
    public BackBtn() {
        initComponents();

        jButton1.setText(null);
        jButton1.setIcon(FontIcon.of(MaterialDesignA.ARROW_LEFT, 35));
        jButton1.putClientProperty("FlatLaf.style", "arc: 99;"); 
        
        jButton1.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout(15, 0));

        jButton1.setForeground(new java.awt.Color(80, 67, 72));
        jButton1.setText("jButton1");
        add(jButton1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Manrope Medium", 0, 16)); // NOI18N
        jLabel1.setText("Back");
        add(jLabel1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
