/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamException;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author KAROL JOHN
 */
public class CameraControl extends javax.swing.JPanel {
    /**
     * Creates new form NewJPanel
     */
    public CameraControl() {
        initComponents();
    }

    public void populateWebcams(List<Webcam> webcams) {
        camerasComboBox.removeAllItems();
        for (var cam: webcams) {
            camerasComboBox.addItem(cam.getName());
        }
    }
    
    public JButton getShutter() {
        return cameraShutterButton;
    }
    
    public JComboBox getCamerasComboBox() {
        return camerasComboBox;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        camerasComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        cameraShutterButton = new org.one.patientmanagement.ui.components.CameraRoundButton();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 40, 30, 40));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        camerasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(camerasComboBox, gridBagConstraints);

        jPanel2.add(jPanel4);

        jPanel1.setMinimumSize(new java.awt.Dimension(82, 50));
        jPanel1.setOpaque(false);
        jPanel1.add(cameraShutterButton);

        jPanel2.add(jPanel1);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.one.patientmanagement.ui.components.CameraRoundButton cameraShutterButton;
    private javax.swing.JComboBox<String> camerasComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
