/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

import java.awt.event.ActionListener;

/**
 *
 * @author KAROL JOHN
 */
public class PatientStartupCard extends javax.swing.JPanel {

    /**
     * Creates new form PatientStartupCard
     */
    public PatientStartupCard() {
        initComponents();
        illustration.putClientProperty("FlatLaf.style", "arc: 8;");
    }
    
    public void setInfoText(String text) {
        infoText.setText(text);
    }
    
    public void setButtonTitle(String text) {
        jButton1.setText(text);
    }
    
    public void setButtonAction(ActionListener l) {
        jButton1.addActionListener(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        illustration = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        infoText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 216, 231));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 216, 231));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel2.setLayout(new java.awt.BorderLayout(0, 15));

        illustration.setBackground(new java.awt.Color(255, 240, 244));

        javax.swing.GroupLayout illustrationLayout = new javax.swing.GroupLayout(illustration);
        illustration.setLayout(illustrationLayout);
        illustrationLayout.setHorizontalGroup(
            illustrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        illustrationLayout.setVerticalGroup(
            illustrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        jPanel2.add(illustration, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        jPanel1.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(137, 74, 105));
        jButton1.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Existing Patient");
        jButton1.setPreferredSize(new java.awt.Dimension(250, 60));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);

        jPanel2.add(jPanel1, java.awt.BorderLayout.SOUTH);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setOpaque(false);

        infoText.setFont(new java.awt.Font("Manrope", 0, 10)); // NOI18N
        infoText.setForeground(new java.awt.Color(126, 111, 116));
        infoText.setText("Check in  with your appointment or records.");
        jPanel3.add(infoText);

        add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel illustration;
    private javax.swing.JLabel infoText;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
