/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.components;

import java.util.List;

/**
 *
 * @author KAROL JOHN
 */
public final class StepProgress extends javax.swing.JPanel {

    /**
     * Creates new form StepProgress
     */
    public StepProgress() {
        initComponents();

        jPanel1.putClientProperty("FlatLaf.style", "arc: 999;");
        jPanel2.putClientProperty("FlatLaf.style", "arc: 999;");
        jPanel3.putClientProperty("FlatLaf.style", "arc: 999;");
        
        setProgress(0);
    }
    
    public void remmoveBack() {
        remove(backPanel);
        revalidate();
        repaint();
    }

    public void setProgress(int step) {
        var panels = List.of(jPanel1, jPanel2, jPanel3);

        for (int i = 0; i < panels.size(); i++) {
            var panel = panels.get(i);

            if (i <= step) {
                panel.setBackground(new java.awt.Color(127, 85, 57));
            } else panel.setBackground(new java.awt.Color(229, 214, 218));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        backPanel = new javax.swing.JPanel();
        backBtn1 = new org.one.patientmanagement.ui.components.BackBtn();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 0, 30));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 6));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(1118, 6));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel1.setBackground(new java.awt.Color(127, 85, 57));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(229, 214, 218));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(229, 214, 218));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel3);

        add(jPanel4);

        backPanel.setOpaque(false);
        backPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 15));

        backBtn1.setOpaque(false);
        backPanel.add(backBtn1);

        add(backPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.one.patientmanagement.ui.components.BackBtn backBtn1;
    private javax.swing.JPanel backPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
