/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.view;

/**
 *
 * @author Lei
 */
public class PatientSignUp extends javax.swing.JPanel {

    /**
     * Creates new form ExistingAcctLogin
     */
    public PatientSignUp() {
        initComponents();
        
        submitButton.putClientProperty("FlatLaf.style", "arc: 999;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuItem1 = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        stepProgress1 = new org.one.patientmanagement.ui.components.StepProgress();
        jPanel2 = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        formContainer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Existing_Email = new javax.swing.JLabel();
        Username_Field = new javax.swing.JTextField();
        Note = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Existing_Email2 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        Existing_Email1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        submitButton = new javax.swing.JButton();
        backdrop2 = new org.one.patientmanagement.ui.components.Backdrop();

        jMenuItem1.setText("jMenuItem1");

        setBackground(new java.awt.Color(255, 248, 248));
        setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setEnabled(false);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(stepProgress1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        formPanel.setBackground(new java.awt.Color(250, 234, 238));
        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 70, 70, 70));
        formPanel.setPreferredSize(new java.awt.Dimension(550, 500));
        formPanel.setLayout(new java.awt.BorderLayout(0, 50));

        formContainer.setOpaque(false);
        formContainer.setPreferredSize(new java.awt.Dimension(1166, 300));
        formContainer.setLayout(new java.awt.GridBagLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout(0, 10));

        Existing_Email.setFont(new java.awt.Font("Manrope SemiBold", 0, 20)); // NOI18N
        Existing_Email.setText("Email or Phone Number");
        Existing_Email.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel3.add(Existing_Email, java.awt.BorderLayout.PAGE_START);

        Username_Field.setBackground(new java.awt.Color(255, 240, 244));
        Username_Field.setFont(new java.awt.Font("Manrope", 0, 16)); // NOI18N
        Username_Field.setText("Email / Phone Number");
        jPanel3.add(Username_Field, java.awt.BorderLayout.CENTER);

        Note.setFont(new java.awt.Font("Manrope", 0, 10)); // NOI18N
        Note.setText("This will serve as your main contact");
        jPanel3.add(Note, java.awt.BorderLayout.PAGE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 284;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 25, 0);
        formContainer.add(jPanel3, gridBagConstraints);

        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(533, 68));
        jPanel5.setLayout(new java.awt.BorderLayout(0, 10));

        Existing_Email2.setFont(new java.awt.Font("Manrope SemiBold", 0, 20)); // NOI18N
        Existing_Email2.setText("Confirm PIN");
        Existing_Email2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel5.add(Existing_Email2, java.awt.BorderLayout.PAGE_START);

        jPasswordField2.setBackground(new java.awt.Color(255, 240, 244));
        jPasswordField2.setFont(new java.awt.Font("Manrope", 0, 16)); // NOI18N
        jPasswordField2.setText("123456");
        jPasswordField2.addActionListener(this::jPasswordField2ActionPerformed);
        jPanel5.add(jPasswordField2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        formContainer.add(jPanel5, gridBagConstraints);

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(533, 68));
        jPanel4.setLayout(new java.awt.BorderLayout(0, 10));

        Existing_Email1.setFont(new java.awt.Font("Manrope SemiBold", 0, 20)); // NOI18N
        Existing_Email1.setText("Create PIN");
        Existing_Email1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel4.add(Existing_Email1, java.awt.BorderLayout.PAGE_START);

        jPasswordField1.setBackground(new java.awt.Color(255, 240, 244));
        jPasswordField1.setFont(new java.awt.Font("Manrope", 0, 16)); // NOI18N
        jPasswordField1.setText("123456");
        jPasswordField1.addActionListener(this::jPasswordField1ActionPerformed);
        jPanel4.add(jPasswordField1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        formContainer.add(jPanel4, gridBagConstraints);

        formPanel.add(formContainer, java.awt.BorderLayout.CENTER);

        submitButton.setBackground(new java.awt.Color(137, 74, 105));
        submitButton.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Proceed");
        submitButton.setPreferredSize(new java.awt.Dimension(95, 55));
        submitButton.addActionListener(this::submitButtonActionPerformed);
        formPanel.add(submitButton, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(formPanel, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel1);
        jSplitPane1.setLeftComponent(backdrop2);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Existing_Email;
    private javax.swing.JLabel Existing_Email1;
    private javax.swing.JLabel Existing_Email2;
    private javax.swing.JLabel Note;
    private javax.swing.JTextField Username_Field;
    private org.one.patientmanagement.ui.components.Backdrop backdrop2;
    private javax.swing.JPanel formContainer;
    private javax.swing.JPanel formPanel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSplitPane jSplitPane1;
    private org.one.patientmanagement.ui.components.StepProgress stepProgress1;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}