/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.view;

/**
 *
 * @author KAROL JOHN
 */
public class PatientStartupView extends javax.swing.JPanel {

    /**
     * Creates new form PatientStartupView
     */
    public PatientStartupView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        backdrop1 = new org.one.patientmanagement.ui.components.Backdrop();
        jPanel1 = new javax.swing.JPanel();
        stepProgress1 = new org.one.patientmanagement.ui.components.StepProgress();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        patientStartupCard1 = new org.one.patientmanagement.ui.components.PatientStartupCard();
        patientStartupCard2 = new org.one.patientmanagement.ui.components.PatientStartupCard();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 248, 248));
        setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setDividerSize(0);
        jSplitPane1.setResizeWeight(0.1);
        jSplitPane1.setEnabled(false);
        jSplitPane1.setOpaque(false);
        jSplitPane1.setLeftComponent(backdrop1);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(stepProgress1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 31)); // NOI18N
        jLabel1.setText("How can we help you today?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel2.add(jLabel1, gridBagConstraints);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 20, 0));
        jPanel3.add(patientStartupCard1);
        jPanel3.add(patientStartupCard2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 119;
        gridBagConstraints.ipady = 257;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 0, 39, 0);
        jPanel2.add(jPanel3, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Manrope Medium", 0, 16)); // NOI18N
        jLabel2.setText("Need help? Ask our staff for assistance.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel2, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel1);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.one.patientmanagement.ui.components.Backdrop backdrop1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private org.one.patientmanagement.ui.components.PatientStartupCard patientStartupCard1;
    private org.one.patientmanagement.ui.components.PatientStartupCard patientStartupCard2;
    private org.one.patientmanagement.ui.components.StepProgress stepProgress1;
    // End of variables declaration//GEN-END:variables
}
