/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui.view;

/**
 *
 * @author KAROL JOHN
 */
public class ServiceSelectionView extends javax.swing.JPanel {

    /**
     * Creates new form ServiceSelectionView
     */
    public ServiceSelectionView() {
        initComponents();
        
        cancelButton.putClientProperty("FlatLaf.style", "arc: 999;");
        continueButton1.putClientProperty("FlatLaf.style", "arc: 999;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        stepProgress1 = new org.one.patientmanagement.ui.components.StepProgress();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        General_Button1 = new javax.swing.JButton();
        General_Button2 = new javax.swing.JButton();
        General_Button3 = new javax.swing.JButton();
        General_Button = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        continueButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(0, 507));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jPanel3.setMaximumSize(new java.awt.Dimension(800, 2147483647));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 507));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 690));
        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(stepProgress1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 31)); // NOI18N
        jLabel1.setText("Select a service");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(4, 0, 0, 10));

        General_Button1.setBackground(new java.awt.Color(114, 87, 98));
        General_Button1.setFont(new java.awt.Font("Manrope Medium", 0, 20)); // NOI18N
        General_Button1.setForeground(new java.awt.Color(255, 255, 255));
        General_Button1.setText("General Checkup");
        General_Button1.setPreferredSize(new java.awt.Dimension(530, 65));
        General_Button1.addActionListener(this::General_Button1ActionPerformed);
        jPanel2.add(General_Button1);

        General_Button2.setBackground(new java.awt.Color(250, 234, 238));
        General_Button2.setFont(new java.awt.Font("Manrope Medium", 0, 20)); // NOI18N
        General_Button2.setForeground(new java.awt.Color(114, 87, 98));
        General_Button2.setText("Pediatrics");
        General_Button2.setPreferredSize(new java.awt.Dimension(530, 65));
        General_Button2.addActionListener(this::General_Button2ActionPerformed);
        jPanel2.add(General_Button2);

        General_Button3.setBackground(new java.awt.Color(250, 234, 238));
        General_Button3.setFont(new java.awt.Font("Manrope Medium", 0, 20)); // NOI18N
        General_Button3.setForeground(new java.awt.Color(114, 87, 98));
        General_Button3.setText("Conseling");
        General_Button3.setPreferredSize(new java.awt.Dimension(530, 65));
        General_Button3.addActionListener(this::General_Button3ActionPerformed);
        jPanel2.add(General_Button3);

        General_Button.setBackground(new java.awt.Color(250, 234, 238));
        General_Button.setFont(new java.awt.Font("Manrope Medium", 0, 20)); // NOI18N
        General_Button.setForeground(new java.awt.Color(114, 87, 98));
        General_Button.setText("Physical/Medical Examination");
        General_Button.setPreferredSize(new java.awt.Dimension(530, 65));
        General_Button.addActionListener(this::General_ButtonActionPerformed);
        jPanel2.add(General_Button);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(31, 0, 103, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        cancelButton.setBackground(new java.awt.Color(137, 74, 105));
        cancelButton.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(114, 87, 98));
        cancelButton.setText("Cancel the setup");
        cancelButton.setContentAreaFilled(false);
        cancelButton.setPreferredSize(new java.awt.Dimension(400, 50));
        cancelButton.addActionListener(this::cancelButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel1.add(cancelButton, gridBagConstraints);

        continueButton1.setBackground(new java.awt.Color(137, 74, 105));
        continueButton1.setFont(new java.awt.Font("Manrope SemiBold", 0, 16)); // NOI18N
        continueButton1.setForeground(new java.awt.Color(255, 255, 255));
        continueButton1.setText("Continue");
        continueButton1.setPreferredSize(new java.awt.Dimension(400, 50));
        continueButton1.addActionListener(this::continueButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(continueButton1, gridBagConstraints);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void General_Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_General_Button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_General_Button3ActionPerformed

    private void General_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_General_Button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_General_Button2ActionPerformed

    private void General_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_General_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_General_Button1ActionPerformed

    private void General_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_General_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_General_ButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void continueButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continueButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton General_Button;
    private javax.swing.JButton General_Button1;
    private javax.swing.JButton General_Button2;
    private javax.swing.JButton General_Button3;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton continueButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private org.one.patientmanagement.ui.components.StepProgress stepProgress1;
    // End of variables declaration//GEN-END:variables
}
