/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui;

/**
 *
 * @author Lei
 */
public class Existing_Acct_Appointment_View extends javax.swing.JPanel {

    /**
     * Creates new form Existing_Acct_Appointment_View
     */
    public Existing_Acct_Appointment_View() {
        initComponents();
        applyCustomStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProgBar1 = new javax.swing.JProgressBar();
        ProgBar2 = new javax.swing.JProgressBar();
        ProgBar3 = new javax.swing.JProgressBar();
        Patients_Profile = new javax.swing.JPanel();
        Patient_FN = new javax.swing.JTextField();
        Patient_LN = new javax.swing.JTextField();
        Patient_Bday = new javax.swing.JTextField();
        Patient_Age = new javax.swing.JTextField();
        Patient_Sex = new javax.swing.JTextField();
        Profile_Note = new javax.swing.JLabel();
        Patient_Add = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        Profile = new javax.swing.JLabel();
        Take_Photo = new javax.swing.JLabel();
        Appt_Label = new javax.swing.JLabel();
        Contiue_Cancel_Button = new javax.swing.JPanel();
        Appt_Continue_button = new javax.swing.JButton();
        Appt_Cancel_Button = new javax.swing.JLabel();
        Accout_Credentials = new javax.swing.JPanel();
        Acct_Credentials = new javax.swing.JLabel();
        Username_Panel = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        Username_Input = new javax.swing.JTextField();
        Contact_Note = new javax.swing.JLabel();
        OtherContact_Panel = new javax.swing.JPanel();
        OtherContact = new javax.swing.JLabel();
        Username_Input1 = new javax.swing.JTextField();
        Create_PIN = new javax.swing.JPanel();
        New_PIN = new javax.swing.JPasswordField();
        Confirm_PIN = new javax.swing.JPasswordField();
        New = new javax.swing.JLabel();
        Saving_PIN = new javax.swing.JButton();
        Confirm = new javax.swing.JLabel();
        Scrollable = new javax.swing.JPanel();
        Appt_1 = new javax.swing.JPanel();
        Appt = new javax.swing.JLabel();
        Appt_Date = new javax.swing.JLabel();
        Appt_Doctor = new javax.swing.JPanel();
        Staff = new javax.swing.JLabel();
        Service_Type = new javax.swing.JLabel();
        Doctor = new javax.swing.JLabel();
        Scroll_Bar = new javax.swing.JScrollBar();

        setBackground(new java.awt.Color(255, 248, 248));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProgBar1.setBackground(new java.awt.Color(229, 214, 218));
        ProgBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar1.setPreferredSize(new java.awt.Dimension(220, 15));
        add(ProgBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 35, -1, 10));

        ProgBar2.setBackground(new java.awt.Color(229, 214, 218));
        ProgBar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar2.setPreferredSize(new java.awt.Dimension(220, 15));
        add(ProgBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 35, -1, 10));

        ProgBar3.setBackground(new java.awt.Color(127, 85, 57));
        ProgBar3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar3.setPreferredSize(new java.awt.Dimension(220, 10));
        add(ProgBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 35, -1, -1));

        Patients_Profile.setBackground(new java.awt.Color(255, 240, 244));
        Patients_Profile.setMaximumSize(new java.awt.Dimension(410, 250));
        Patients_Profile.setMinimumSize(new java.awt.Dimension(410, 250));
        Patients_Profile.setPreferredSize(new java.awt.Dimension(410, 250));

        Patient_FN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Patient_FN.setText("First Name");
        Patient_FN.addActionListener(this::Patient_FNActionPerformed);

        Patient_LN.setText("Last Name");
        Patient_LN.addActionListener(this::Patient_LNActionPerformed);

        Patient_Bday.setText("Birthday");
        Patient_Bday.addActionListener(this::Patient_BdayActionPerformed);

        Patient_Age.setText("Age");
        Patient_Age.addActionListener(this::Patient_AgeActionPerformed);

        Patient_Sex.setText("Sex");
        Patient_Sex.addActionListener(this::Patient_SexActionPerformed);

        Profile_Note.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Profile_Note.setText("To update your information, ask the staff");

        Patient_Add.setText("Address");
        Patient_Add.addActionListener(this::Patient_AddActionPerformed);

        Profile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Profile.setText("Your Profile");

        Take_Photo.setText("Take a photo");

        javax.swing.GroupLayout Patients_ProfileLayout = new javax.swing.GroupLayout(Patients_Profile);
        Patients_Profile.setLayout(Patients_ProfileLayout);
        Patients_ProfileLayout.setHorizontalGroup(
            Patients_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Patients_ProfileLayout.createSequentialGroup()
                .addGroup(Patients_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Patients_ProfileLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jRadioButton1)
                        .addGap(56, 56, 56)
                        .addComponent(Take_Photo))
                    .addGroup(Patients_ProfileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Patient_FN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Patient_LN, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Patient_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Patient_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 88, Short.MAX_VALUE))
            .addGroup(Patients_ProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Patients_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Patients_ProfileLayout.createSequentialGroup()
                        .addComponent(Patient_Bday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(Patient_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Profile_Note)
                    .addComponent(Profile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Patients_ProfileLayout.setVerticalGroup(
            Patients_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Patients_ProfileLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Profile)
                .addGap(18, 18, 18)
                .addGroup(Patients_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton1)
                    .addComponent(Take_Photo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Patients_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Patient_FN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Patient_LN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Patient_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Patient_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(Patients_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Patient_Bday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Patient_Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(Profile_Note)
                .addGap(16, 16, 16))
        );

        add(Patients_Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 35, 410, 250));

        Appt_Label.setText("Your Appointment");
        add(Appt_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 98, -1, -1));

        Contiue_Cancel_Button.setBackground(new java.awt.Color(255, 248, 248));

        Appt_Continue_button.setBackground(new java.awt.Color(137, 74, 105));
        Appt_Continue_button.setText("Continue");
        Appt_Continue_button.setMaximumSize(new java.awt.Dimension(390, 50));
        Appt_Continue_button.setMinimumSize(new java.awt.Dimension(390, 50));
        Appt_Continue_button.setPreferredSize(new java.awt.Dimension(390, 50));
        Appt_Continue_button.addActionListener(this::Appt_Continue_buttonActionPerformed);

        Appt_Cancel_Button.setText("Ask the staff to cancel");

        javax.swing.GroupLayout Contiue_Cancel_ButtonLayout = new javax.swing.GroupLayout(Contiue_Cancel_Button);
        Contiue_Cancel_Button.setLayout(Contiue_Cancel_ButtonLayout);
        Contiue_Cancel_ButtonLayout.setHorizontalGroup(
            Contiue_Cancel_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Contiue_Cancel_ButtonLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(Appt_Continue_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(Contiue_Cancel_ButtonLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(Appt_Cancel_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Contiue_Cancel_ButtonLayout.setVerticalGroup(
            Contiue_Cancel_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contiue_Cancel_ButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Appt_Continue_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Appt_Cancel_Button)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        add(Contiue_Cancel_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, 430, -1));

        Accout_Credentials.setBackground(new java.awt.Color(255, 240, 244));
        Accout_Credentials.setPreferredSize(new java.awt.Dimension(410, 440));

        Acct_Credentials.setText("Account credentials");

        Username_Panel.setBackground(new java.awt.Color(255, 240, 244));
        Username_Panel.setMaximumSize(new java.awt.Dimension(260, 80));
        Username_Panel.setMinimumSize(new java.awt.Dimension(260, 80));
        Username_Panel.setPreferredSize(new java.awt.Dimension(260, 80));

        Username.setText("Username");

        Username_Input.setText("Enter your username");
        Username_Input.setMaximumSize(new java.awt.Dimension(290, 50));
        Username_Input.setMinimumSize(new java.awt.Dimension(290, 50));
        Username_Input.setPreferredSize(new java.awt.Dimension(290, 50));
        Username_Input.addActionListener(this::Username_InputActionPerformed);

        Contact_Note.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Contact_Note.setText("This is linked to your main contact.");

        javax.swing.GroupLayout Username_PanelLayout = new javax.swing.GroupLayout(Username_Panel);
        Username_Panel.setLayout(Username_PanelLayout);
        Username_PanelLayout.setHorizontalGroup(
            Username_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Username_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Username_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Username_PanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Contact_Note))
                    .addComponent(Username)
                    .addComponent(Username_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Username_PanelLayout.setVerticalGroup(
            Username_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Username_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contact_Note)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OtherContact_Panel.setBackground(new java.awt.Color(255, 240, 244));
        OtherContact_Panel.setMaximumSize(new java.awt.Dimension(260, 80));
        OtherContact_Panel.setMinimumSize(new java.awt.Dimension(260, 80));

        OtherContact.setText("Other Contact");

        Username_Input1.setText("Enter your username");
        Username_Input1.setMaximumSize(new java.awt.Dimension(290, 50));
        Username_Input1.setMinimumSize(new java.awt.Dimension(290, 50));
        Username_Input1.setPreferredSize(new java.awt.Dimension(290, 50));
        Username_Input1.addActionListener(this::Username_Input1ActionPerformed);

        javax.swing.GroupLayout OtherContact_PanelLayout = new javax.swing.GroupLayout(OtherContact_Panel);
        OtherContact_Panel.setLayout(OtherContact_PanelLayout);
        OtherContact_PanelLayout.setHorizontalGroup(
            OtherContact_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OtherContact_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OtherContact_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OtherContact, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username_Input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        OtherContact_PanelLayout.setVerticalGroup(
            OtherContact_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OtherContact_PanelLayout.createSequentialGroup()
                .addComponent(OtherContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username_Input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Create_PIN.setBackground(new java.awt.Color(255, 240, 244));

        New_PIN.setText("jPasswordField1");
        New_PIN.setMaximumSize(new java.awt.Dimension(150, 50));
        New_PIN.setMinimumSize(new java.awt.Dimension(150, 50));
        New_PIN.setPreferredSize(new java.awt.Dimension(150, 50));
        New_PIN.addActionListener(this::New_PINActionPerformed);

        Confirm_PIN.setText("jPasswordField1");
        Confirm_PIN.setMaximumSize(new java.awt.Dimension(150, 50));
        Confirm_PIN.setMinimumSize(new java.awt.Dimension(150, 50));
        Confirm_PIN.setPreferredSize(new java.awt.Dimension(150, 50));
        Confirm_PIN.addActionListener(this::Confirm_PINActionPerformed);

        New.setText("New PIN");

        Saving_PIN.setBackground(new java.awt.Color(255, 216, 231));
        Saving_PIN.setText("Save new PIN");
        Saving_PIN.setPreferredSize(new java.awt.Dimension(130, 40));

        Confirm.setText("Confirm PIN");

        javax.swing.GroupLayout Create_PINLayout = new javax.swing.GroupLayout(Create_PIN);
        Create_PIN.setLayout(Create_PINLayout);
        Create_PINLayout.setHorizontalGroup(
            Create_PINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create_PINLayout.createSequentialGroup()
                .addGroup(Create_PINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Create_PINLayout.createSequentialGroup()
                        .addGroup(Create_PINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Create_PINLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(New))
                            .addGroup(Create_PINLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(New_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(Create_PINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Create_PINLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(Confirm)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Create_PINLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(Confirm_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Create_PINLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Saving_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        Create_PINLayout.setVerticalGroup(
            Create_PINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Create_PINLayout.createSequentialGroup()
                .addGroup(Create_PINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(New)
                    .addComponent(Confirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Create_PINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(New_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Confirm_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Saving_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout Accout_CredentialsLayout = new javax.swing.GroupLayout(Accout_Credentials);
        Accout_Credentials.setLayout(Accout_CredentialsLayout);
        Accout_CredentialsLayout.setHorizontalGroup(
            Accout_CredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Accout_CredentialsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(Accout_CredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Acct_Credentials)
                    .addGroup(Accout_CredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(OtherContact_Panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Username_Panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                    .addComponent(Create_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Accout_CredentialsLayout.setVerticalGroup(
            Accout_CredentialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Accout_CredentialsLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(Acct_Credentials)
                .addGap(46, 46, 46)
                .addComponent(Username_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OtherContact_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Create_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        add(Accout_Credentials, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 410, -1));

        Scrollable.setBackground(new java.awt.Color(255, 248, 248));
        Scrollable.setMaximumSize(new java.awt.Dimension(500, 500));
        Scrollable.setMinimumSize(new java.awt.Dimension(500, 500));
        Scrollable.setPreferredSize(new java.awt.Dimension(500, 500));

        Appt_1.setBackground(new java.awt.Color(255, 248, 248));
        Appt_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Appt_1.setMaximumSize(new java.awt.Dimension(380, 115));
        Appt_1.setMinimumSize(new java.awt.Dimension(380, 115));
        Appt_1.setPreferredSize(new java.awt.Dimension(380, 115));

        Appt.setText("Diagnostic");

        Appt_Date.setText("Date of Appt");

        Appt_Doctor.setBackground(new java.awt.Color(250, 234, 238));
        Appt_Doctor.setMaximumSize(new java.awt.Dimension(340, 80));
        Appt_Doctor.setMinimumSize(new java.awt.Dimension(340, 80));
        Appt_Doctor.setPreferredSize(new java.awt.Dimension(340, 80));

        Staff.setText("Referred by Dr.");

        Service_Type.setText("General Check up");

        Doctor.setText("Dr. House");

        javax.swing.GroupLayout Appt_DoctorLayout = new javax.swing.GroupLayout(Appt_Doctor);
        Appt_Doctor.setLayout(Appt_DoctorLayout);
        Appt_DoctorLayout.setHorizontalGroup(
            Appt_DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Appt_DoctorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Appt_DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Staff)
                    .addComponent(Service_Type)
                    .addComponent(Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        Appt_DoctorLayout.setVerticalGroup(
            Appt_DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Appt_DoctorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Staff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Service_Type)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Doctor)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Appt_1Layout = new javax.swing.GroupLayout(Appt_1);
        Appt_1.setLayout(Appt_1Layout);
        Appt_1Layout.setHorizontalGroup(
            Appt_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Appt_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Appt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Appt_Date)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Appt_1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(Appt_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        Appt_1Layout.setVerticalGroup(
            Appt_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Appt_1Layout.createSequentialGroup()
                .addGroup(Appt_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Appt)
                    .addComponent(Appt_Date))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Appt_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ScrollableLayout = new javax.swing.GroupLayout(Scrollable);
        Scrollable.setLayout(ScrollableLayout);
        ScrollableLayout.setHorizontalGroup(
            ScrollableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrollableLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(Appt_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(Scroll_Bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ScrollableLayout.setVerticalGroup(
            ScrollableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScrollableLayout.createSequentialGroup()
                .addComponent(Scroll_Bar, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(ScrollableLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Appt_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        add(Scrollable, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 500, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void Patient_FNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_FNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_FNActionPerformed

    private void Patient_LNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_LNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_LNActionPerformed

    private void Patient_BdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_BdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_BdayActionPerformed

    private void Patient_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_AgeActionPerformed

    private void Patient_SexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_SexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_SexActionPerformed

    private void Patient_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_AddActionPerformed

    private void Appt_Continue_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Appt_Continue_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Appt_Continue_buttonActionPerformed

    private void Username_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_InputActionPerformed

    private void Username_Input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_Input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_Input1ActionPerformed

    private void Confirm_PINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_PINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Confirm_PINActionPerformed

    private void New_PINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_PINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_New_PINActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accout_Credentials;
    private javax.swing.JLabel Acct_Credentials;
    private javax.swing.JLabel Appt;
    private javax.swing.JPanel Appt_1;
    private javax.swing.JLabel Appt_Cancel_Button;
    private javax.swing.JButton Appt_Continue_button;
    private javax.swing.JLabel Appt_Date;
    private javax.swing.JPanel Appt_Doctor;
    private javax.swing.JLabel Appt_Label;
    private javax.swing.JLabel Confirm;
    private javax.swing.JPasswordField Confirm_PIN;
    private javax.swing.JLabel Contact_Note;
    private javax.swing.JPanel Contiue_Cancel_Button;
    private javax.swing.JPanel Create_PIN;
    private javax.swing.JLabel Doctor;
    private javax.swing.JLabel New;
    private javax.swing.JPasswordField New_PIN;
    private javax.swing.JLabel OtherContact;
    private javax.swing.JPanel OtherContact_Panel;
    private javax.swing.JTextField Patient_Add;
    private javax.swing.JTextField Patient_Age;
    private javax.swing.JTextField Patient_Bday;
    private javax.swing.JTextField Patient_FN;
    private javax.swing.JTextField Patient_LN;
    private javax.swing.JTextField Patient_Sex;
    private javax.swing.JPanel Patients_Profile;
    private javax.swing.JLabel Profile;
    private javax.swing.JLabel Profile_Note;
    private javax.swing.JProgressBar ProgBar1;
    private javax.swing.JProgressBar ProgBar2;
    private javax.swing.JProgressBar ProgBar3;
    private javax.swing.JButton Saving_PIN;
    private javax.swing.JScrollBar Scroll_Bar;
    private javax.swing.JPanel Scrollable;
    private javax.swing.JLabel Service_Type;
    private javax.swing.JLabel Staff;
    private javax.swing.JLabel Take_Photo;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField Username_Input;
    private javax.swing.JTextField Username_Input1;
    private javax.swing.JPanel Username_Panel;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables

    private void applyCustomStyles() {
    // --- 1. COLORS ---
    java.awt.Color primaryDark = new java.awt.Color(33, 25, 28);      
    java.awt.Color continueBG = new java.awt.Color(137, 74, 105); // [137, 74, 105]
    java.awt.Color cancelColor = new java.awt.Color(114, 87, 98);    

    // --- 2. CENTERING LOGIC (Relative to Scrollable) ---
    add(Appt_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 98, 300, -1));
    Appt_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    Appt_Label.setFont(new java.awt.Font("Poppins Medium", java.awt.Font.PLAIN, 32));

    add(Contiue_Cancel_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 650, 430, -1));

    // --- 3. BORDER RADIUS UPDATES ---
    // Account Credentials main panel gets 28px
    Accout_Credentials.setBorder(new RoundedBorder(28));
    Accout_Credentials.setBackground(new java.awt.Color(255, 240, 244));
    
    // Create_PIN - Removing custom border to prevent overlap with parent
    Create_PIN.setBorder(null); 
    Create_PIN.setOpaque(false);

    // Appt_Doctor (The card inside the scrollable) gets 18px
    Appt_Doctor.setBorder(new RoundedBorder(18));
    
    // Saving_PIN button gets 12px
    Saving_PIN.setBorder(new RoundedBorder(12));

    // Patient Profile panel gets 28px
    Patients_Profile.setBorder(new RoundedBorder(28));

    // --- 4. BUTTON STYLING (Appt_Continue_button) ---
    Appt_Continue_button.setFont(new java.awt.Font("Manrope SemiBold", java.awt.Font.PLAIN, 16));
    Appt_Continue_button.setBackground(continueBG);
    Appt_Continue_button.setForeground(java.awt.Color.WHITE); // Font color White
    Appt_Continue_button.setOpaque(true);
    Appt_Continue_button.setContentAreaFilled(true); // Enabled to show BG color
    Appt_Continue_button.setBorder(new RoundedBorder(71)); 

    // --- 5. FONT & TEXT FIELD CLEANUP ---
    java.awt.Font subtitleFont = new java.awt.Font("Poppins Medium", java.awt.Font.PLAIN, 18);
    Acct_Credentials.setFont(subtitleFont);
    Profile.setFont(subtitleFont);

    java.awt.Font manropeSemi14 = new java.awt.Font("Manrope SemiBold", java.awt.Font.PLAIN, 14);
    javax.swing.JTextField[] fields = {
        Patient_FN, Patient_LN, Patient_Sex, Patient_Age, Patient_Bday, Patient_Add
    };
    for (javax.swing.JTextField field : fields) {
        field.setFont(manropeSemi14);
        field.setBorder(null);
        field.setOpaque(false);
    }
}
    class RoundedBorder implements javax.swing.border.Border {
    private int radius;
    private java.awt.Color borderColor;

    RoundedBorder(int radius) {
        this.radius = radius;
        this.borderColor = new java.awt.Color(137, 74, 105); 
    }

    @Override
    public java.awt.Insets getBorderInsets(java.awt.Component c) {
        return new java.awt.Insets(radius/3, radius/2, radius/3, radius/2);
    }

    @Override
    public boolean isBorderOpaque() {
        return true;
    }

    @Override
    public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
        java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
        g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
        
        // If the component is a button with a background color, we draw the fill
        if (c.isOpaque() && c.getBackground() != null) {
            g2d.setColor(c.getBackground());
            g2d.fillRoundRect(x, y, width - 1, height - 1, radius, radius);
        }
        
        g2d.setColor(borderColor);
        g2d.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
    }
}
  
}


