/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui;

/**
 *
 * @author Lei
 */
public class ExistingAcctLogin extends javax.swing.JPanel {

    /**
     * Creates new form ExistingAcctLogin
     */
    public ExistingAcctLogin() {
        initComponents();
        Styling();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Existing_Login = new javax.swing.JPanel();
        Login_Button = new javax.swing.JButton();
        Existing_Email = new javax.swing.JLabel();
        Existing_PIN = new javax.swing.JLabel();
        Username_Field = new javax.swing.JTextField();
        PIN_Pass = new javax.swing.JPasswordField();
        Backdrop = new javax.swing.JPanel();
        Navigator = new javax.swing.JPanel();
        ProgBar4 = new javax.swing.JProgressBar();
        ProgBar5 = new javax.swing.JProgressBar();
        ProgBar6 = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(255, 248, 248));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Existing_Login.setBackground(new java.awt.Color(250, 234, 238));
        Existing_Login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 234, 238)));
        Existing_Login.setPreferredSize(new java.awt.Dimension(550, 450));

        Login_Button.setBackground(new java.awt.Color(137, 74, 105));
        Login_Button.setText("Login");
        Login_Button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Login_Button.setPreferredSize(new java.awt.Dimension(350, 23));
        Login_Button.addActionListener(this::Login_ButtonActionPerformed);

        Existing_Email.setText("Email or Phone Number");

        Existing_PIN.setText("PIN");

        Username_Field.setText("Email / Phone Number");

        PIN_Pass.setText("jPasswordField1");

        javax.swing.GroupLayout Existing_LoginLayout = new javax.swing.GroupLayout(Existing_Login);
        Existing_Login.setLayout(Existing_LoginLayout);
        Existing_LoginLayout.setHorizontalGroup(
            Existing_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Existing_LoginLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(Existing_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Existing_Email)
                    .addComponent(Existing_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PIN_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        Existing_LoginLayout.setVerticalGroup(
            Existing_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Existing_LoginLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Existing_Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Existing_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PIN_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        add(Existing_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 175, 549, -1));

        Backdrop.setMinimumSize(null);
        Backdrop.setPreferredSize(new java.awt.Dimension(450, 800));
        Backdrop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(Backdrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 800));

        Navigator.setBackground(new java.awt.Color(255, 248, 248));
        Navigator.setMaximumSize(new java.awt.Dimension(720, 10));
        Navigator.setMinimumSize(new java.awt.Dimension(720, 10));
        Navigator.setPreferredSize(new java.awt.Dimension(720, 10));
        Navigator.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        ProgBar4.setBackground(new java.awt.Color(229, 214, 218));
        ProgBar4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar4.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar4);

        ProgBar5.setBackground(new java.awt.Color(127, 85, 57));
        ProgBar5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar5.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar5);

        ProgBar6.setBackground(new java.awt.Color(229, 214, 218));
        ProgBar6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar6.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar6);

        add(Navigator, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 720, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backdrop;
    private javax.swing.JLabel Existing_Email;
    private javax.swing.JPanel Existing_Login;
    private javax.swing.JLabel Existing_PIN;
    private javax.swing.JButton Login_Button;
    private javax.swing.JPanel Navigator;
    private javax.swing.JPasswordField PIN_Pass;
    private javax.swing.JProgressBar ProgBar4;
    private javax.swing.JProgressBar ProgBar5;
    private javax.swing.JProgressBar ProgBar6;
    private javax.swing.JTextField Username_Field;
    // End of variables declaration//GEN-END:variables
private void Styling() {
    java.awt.Font manrope = new java.awt.Font("Manrope", java.awt.Font.BOLD, 18);
    Existing_Email.setFont(manrope);
    Existing_PIN.setFont(manrope);
    Username_Field.setText("Enter your Email");

    // 1. THE BUTTON FIX
    Login_Button.setForeground(java.awt.Color.WHITE);
    Login_Button.setFocusPainted(false);
    Login_Button.setContentAreaFilled(false); // Prevents default square background
    Login_Button.setOpaque(false);

    // We override the Border to draw the background AND ensure text stays on top
    Login_Button.setBorder(new javax.swing.border.AbstractBorder() {
        @Override
        public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
            
            // Draw the Purple Background shape
            g2.setColor(new java.awt.Color(137, 74, 105));
            g2.fillRoundRect(x, y, width - 1, height - 1, 40, 40); 
            
            // Draw the text manually to ensure it's visible and centered
            g2.setColor(java.awt.Color.WHITE);
            java.awt.FontMetrics fm = g2.getFontMetrics(c.getFont());
            String text = "Login";
            int textX = (width - fm.stringWidth(text)) / 2;
            int textY = (height - fm.getHeight()) / 2 + fm.getAscent();
            g2.drawString(text, textX, textY);
            
            g2.dispose();
        }
    });

    // 2. THE PANEL (With border matching panel color)
    Existing_Login.setOpaque(false); 
    Existing_Login.setBorder(new javax.swing.border.AbstractBorder() {
        @Override
        public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
            
            java.awt.Color panelColor = new java.awt.Color(250, 234, 238);
            g2.setColor(panelColor);
            
            // Fill and Draw (both same color = invisible border)
            g2.fillRoundRect(x, y, width - 1, height - 1, 28, 28);
            g2.drawRoundRect(x, y, width - 1, height - 1, 28, 28);
            
            g2.dispose();
        }
    });
}}