/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui;

/**
 *
 * @author Lei
 */
public class LoginPatientsView extends javax.swing.JPanel {

    /**
     * Creates new form LoginPatientsView
     */
    public LoginPatientsView() {
        initComponents();
        
        java.awt.Color themeColor = new java.awt.Color(137, 74, 105);
        java.awt.Font manrope = new java.awt.Font("Manrope SemiBold", java.awt.Font.PLAIN, 14);

        // Style Buttons
        New_Login_Button.setBackground(themeColor);
        New_Login_Button.setForeground(java.awt.Color.WHITE);
        New_Login_Button.setFont(manrope);
        
        Exist_Login_Button.setBackground(themeColor);
        Exist_Login_Button.setForeground(java.awt.Color.WHITE);
        Exist_Login_Button.setFont(manrope);

        stylePillButton(Exist_Login_Button);
        stylePillButton(New_Login_Button);

        // PASTE THIS: Style the Cards
        styleCard(Exist_Acct_Card);
        styleCard(New_Acct_Card);
    }

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        Backdrop = new javax.swing.JPanel();
        Navigator = new javax.swing.JPanel();
        ProgBar1 = new javax.swing.JProgressBar();
        ProgBar2 = new javax.swing.JProgressBar();
        ProgBar3 = new javax.swing.JProgressBar();
        Card_Containers = new javax.swing.JPanel();
        Exist_Acct_Card = new javax.swing.JPanel();
        Exist_Login_Button = new javax.swing.JButton();
        Exist_Card_Image = new javax.swing.JPanel();
        New_Acct_Card = new javax.swing.JPanel();
        New_Card_Image = new javax.swing.JPanel();
        New_Login_Button = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 248, 248));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Backdrop.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        Backdrop.setPreferredSize(new java.awt.Dimension(450, 800));
        Backdrop.setLayout(new java.awt.BorderLayout());
        add(Backdrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Navigator.setBackground(new java.awt.Color(255, 248, 248));
        Navigator.setMaximumSize(new java.awt.Dimension(720, 10));
        Navigator.setMinimumSize(new java.awt.Dimension(720, 10));
        Navigator.setPreferredSize(new java.awt.Dimension(720, 10));
        Navigator.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        ProgBar1.setBackground(new java.awt.Color(127, 85, 57));
        ProgBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar1.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar1);

        ProgBar2.setBackground(new java.awt.Color(229, 214, 218));
        ProgBar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar2.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar2);

        ProgBar3.setBackground(new java.awt.Color(229, 214, 218));
        ProgBar3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar3.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar3);

        add(Navigator, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 720, 20));

        Card_Containers.setOpaque(false);
        Card_Containers.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 50));

        Exist_Acct_Card.setBackground(new java.awt.Color(255, 216, 231));
        Exist_Acct_Card.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Exist_Acct_Card.setPreferredSize(new java.awt.Dimension(250, 330));

        Exist_Login_Button.setBackground(new java.awt.Color(137, 74, 105));
        Exist_Login_Button.setText("Existing Patient");
        Exist_Login_Button.setBorder(null);
        Exist_Login_Button.setPreferredSize(new java.awt.Dimension(186, 50));

        Exist_Card_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Exist_Card_Image.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout Exist_Card_ImageLayout = new javax.swing.GroupLayout(Exist_Card_Image);
        Exist_Card_Image.setLayout(Exist_Card_ImageLayout);
        Exist_Card_ImageLayout.setHorizontalGroup(
            Exist_Card_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        Exist_Card_ImageLayout.setVerticalGroup(
            Exist_Card_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Exist_Acct_CardLayout = new javax.swing.GroupLayout(Exist_Acct_Card);
        Exist_Acct_Card.setLayout(Exist_Acct_CardLayout);
        Exist_Acct_CardLayout.setHorizontalGroup(
            Exist_Acct_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Exist_Acct_CardLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Exist_Card_Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(Exist_Acct_CardLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Exist_Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        Exist_Acct_CardLayout.setVerticalGroup(
            Exist_Acct_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Exist_Acct_CardLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Exist_Card_Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Exist_Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        Card_Containers.add(Exist_Acct_Card);

        New_Acct_Card.setBackground(new java.awt.Color(255, 216, 231));
        New_Acct_Card.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        New_Acct_Card.setPreferredSize(new java.awt.Dimension(250, 330));

        New_Card_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        New_Card_Image.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout New_Card_ImageLayout = new javax.swing.GroupLayout(New_Card_Image);
        New_Card_Image.setLayout(New_Card_ImageLayout);
        New_Card_ImageLayout.setHorizontalGroup(
            New_Card_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        New_Card_ImageLayout.setVerticalGroup(
            New_Card_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        New_Login_Button.setBackground(new java.awt.Color(137, 74, 105));
        New_Login_Button.setText("New Patient");
        New_Login_Button.setBorder(null);
        New_Login_Button.setPreferredSize(new java.awt.Dimension(186, 50));
        New_Login_Button.addActionListener(this::New_Login_ButtonActionPerformed);

        javax.swing.GroupLayout New_Acct_CardLayout = new javax.swing.GroupLayout(New_Acct_Card);
        New_Acct_Card.setLayout(New_Acct_CardLayout);
        New_Acct_CardLayout.setHorizontalGroup(
            New_Acct_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(New_Acct_CardLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(New_Acct_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(New_Card_Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(New_Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        New_Acct_CardLayout.setVerticalGroup(
            New_Acct_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, New_Acct_CardLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(New_Card_Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(New_Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        Card_Containers.add(New_Acct_Card);

        add(Card_Containers, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 680, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void New_Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_Login_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_New_Login_ButtonActionPerformed
        private void stylePillButton(javax.swing.JButton button) {
        button.setFocusPainted(false);
        button.setBorderPainted(false); 
        button.setContentAreaFilled(false);
        button.setOpaque(false);

        button.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), c.getHeight(), c.getHeight());
                
                g2.dispose();
                
                // 2. Draw the actual text/label
                super.paint(g, c);
            }
        });
        }
        
        private void styleCard(javax.swing.JPanel card) {
        card.setOpaque(false);
        card.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        card.setUI(new javax.swing.plaf.basic.BasicPanelUI() {
            @Override
            public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Set the pink color
                g2.setColor(new java.awt.Color(255, 216, 231));
                // Draw the rounded rectangle
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 30, 30);

                g2.dispose();
                super.paint(g, c);
            }
        });
    }

    class RoundedPanel extends javax.swing.JPanel {
        private int radius;
        public RoundedPanel(int radius) {
            this.radius = radius;
            setOpaque(false);
        }
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(getBackground());
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), radius, radius);
            g2.dispose();
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backdrop;
    private javax.swing.JPanel Card_Containers;
    private javax.swing.JPanel Exist_Acct_Card;
    private javax.swing.JPanel Exist_Card_Image;
    private javax.swing.JButton Exist_Login_Button;
    private javax.swing.JPanel Navigator;
    private javax.swing.JPanel New_Acct_Card;
    private javax.swing.JPanel New_Card_Image;
    private javax.swing.JButton New_Login_Button;
    private javax.swing.JProgressBar ProgBar1;
    private javax.swing.JProgressBar ProgBar2;
    private javax.swing.JProgressBar ProgBar3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
