/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui;

/**
 *
 * @author Lei
 */
public class New_Acct_Scheduling extends javax.swing.JPanel {

    /**
     * Creates new form New_Acct_Scheduling
     */
    public New_Acct_Scheduling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Navigator = new javax.swing.JPanel();
        ProgBar4 = new javax.swing.JProgressBar();
        ProgBar5 = new javax.swing.JProgressBar();
        ProgBar6 = new javax.swing.JProgressBar();
        Select_Day_Doctor_Panel = new javax.swing.JPanel();
        Selecting_Day = new javax.swing.JPanel();
        Day_Panel = new javax.swing.JPanel();
        Date = new javax.swing.JPanel();
        Month = new javax.swing.JLabel();
        Day = new javax.swing.JLabel();
        Day_Number = new javax.swing.JPanel();
        Morning = new javax.swing.JPanel();
        Afternoon = new javax.swing.JPanel();
        Both = new javax.swing.JPanel();
        Day_Queue_Nav = new javax.swing.JPanel();
        Select_Day = new javax.swing.JLabel();
        Queue_color = new javax.swing.JPanel();
        Morning_color_queue = new javax.swing.JPanel();
        Afternoon_Queue = new javax.swing.JLabel();
        Afternoon_color_queue = new javax.swing.JPanel();
        Morning_Queue = new javax.swing.JLabel();
        Both_queue = new javax.swing.JPanel();
        Both_Sched_Queue = new javax.swing.JLabel();
        Doctor_Avail = new javax.swing.JPanel();
        Date_of_Appt = new javax.swing.JPanel();
        Day_of_Appt = new javax.swing.JLabel();
        Select_Doctor = new javax.swing.JPanel();
        Pick_Doctor = new javax.swing.JLabel();
        Doctor = new javax.swing.JPanel();
        Circle = new javax.swing.JPanel();
        Doctor_Role = new javax.swing.JLabel();
        Doctor_Name = new javax.swing.JLabel();
        Day_ScrollBar = new javax.swing.JScrollBar();
        Doctor_ScrollBar = new javax.swing.JScrollBar();
        Timezone = new javax.swing.JPanel();
        Morning_Time = new javax.swing.JPanel();
        Morning_Image = new javax.swing.JPanel();
        Morning_Label = new javax.swing.JLabel();
        Morning_button = new javax.swing.JToggleButton();
        Afternoon_Time = new javax.swing.JPanel();
        Afternoon_ToggleButton = new javax.swing.JToggleButton();
        Select_Time = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Schedule_Note = new javax.swing.JTextArea();
        Profile = new javax.swing.JPanel();
        Set_Acct = new javax.swing.JPanel();
        User_Profile_Inputs = new javax.swing.JPanel();
        User_FN = new javax.swing.JLabel();
        FN_Input = new javax.swing.JTextField();
        User_LN = new javax.swing.JLabel();
        LN_Input = new javax.swing.JTextField();
        User_Address = new javax.swing.JLabel();
        Address_Input = new javax.swing.JTextField();
        User_Contact = new javax.swing.JLabel();
        Contact_Input = new javax.swing.JTextField();
        Set_Profile = new javax.swing.JPanel();
        Bilog = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Take_Photo = new javax.swing.JButton();
        Photo_Icon = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Bday_Sex_Blood = new javax.swing.JPanel();
        User_Bday = new javax.swing.JLabel();
        Bday_TextField = new javax.swing.JTextField();
        User_Sex = new javax.swing.JLabel();
        Sex_List = new javax.swing.JComboBox<>();
        User_BloodType = new javax.swing.JLabel();
        BloodType_List = new javax.swing.JComboBox<>();
        Continue_Button = new javax.swing.JButton();
        Cancel_button = new javax.swing.JButton();
        Back_button = new javax.swing.JButton();
        Continue_Cancel_Panel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 248, 248));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Navigator.setBackground(new java.awt.Color(255, 248, 248));
        Navigator.setMaximumSize(new java.awt.Dimension(720, 10));
        Navigator.setMinimumSize(new java.awt.Dimension(720, 10));
        Navigator.setPreferredSize(new java.awt.Dimension(720, 10));
        Navigator.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        ProgBar4.setBackground(new java.awt.Color(229, 214, 218));
        ProgBar4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar4.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar4);

        ProgBar5.setBackground(new java.awt.Color(229, 214, 218));
        ProgBar5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar5.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar5);

        ProgBar6.setBackground(new java.awt.Color(127, 85, 57));
        ProgBar6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar6.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar6);

        add(Navigator, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 720, 20));

        Select_Day_Doctor_Panel.setBackground(new java.awt.Color(255, 240, 244));
        Select_Day_Doctor_Panel.setMaximumSize(new java.awt.Dimension(1100, 250));
        Select_Day_Doctor_Panel.setMinimumSize(new java.awt.Dimension(1100, 250));
        Select_Day_Doctor_Panel.setPreferredSize(new java.awt.Dimension(1100, 250));

        Selecting_Day.setBackground(new java.awt.Color(255, 240, 244));
        Selecting_Day.setMaximumSize(new java.awt.Dimension(780, 240));
        Selecting_Day.setMinimumSize(new java.awt.Dimension(780, 240));
        Selecting_Day.setPreferredSize(new java.awt.Dimension(780, 240));

        Day_Panel.setPreferredSize(new java.awt.Dimension(134, 170));

        Date.setBackground(new java.awt.Color(241, 222, 228));
        Date.setMaximumSize(new java.awt.Dimension(100, 120));
        Date.setMinimumSize(new java.awt.Dimension(100, 120));

        Month.setText("Month");

        Day.setText("Day");

        Day_Number.setBackground(new java.awt.Color(51, 51, 255));
        Day_Number.setMaximumSize(new java.awt.Dimension(42, 42));
        Day_Number.setMinimumSize(new java.awt.Dimension(42, 42));
        Day_Number.setPreferredSize(new java.awt.Dimension(42, 42));

        javax.swing.GroupLayout Day_NumberLayout = new javax.swing.GroupLayout(Day_Number);
        Day_Number.setLayout(Day_NumberLayout);
        Day_NumberLayout.setHorizontalGroup(
            Day_NumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        Day_NumberLayout.setVerticalGroup(
            Day_NumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DateLayout = new javax.swing.GroupLayout(Date);
        Date.setLayout(DateLayout);
        DateLayout.setHorizontalGroup(
            DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DateLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Day, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Day_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        DateLayout.setVerticalGroup(
            DateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DateLayout.createSequentialGroup()
                .addComponent(Month)
                .addGap(18, 18, 18)
                .addComponent(Day_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Day)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Morning.setBackground(new java.awt.Color(254, 176, 211));
        Morning.setMaximumSize(new java.awt.Dimension(12, 12));
        Morning.setMinimumSize(new java.awt.Dimension(12, 12));
        Morning.setPreferredSize(new java.awt.Dimension(12, 12));

        javax.swing.GroupLayout MorningLayout = new javax.swing.GroupLayout(Morning);
        Morning.setLayout(MorningLayout);
        MorningLayout.setHorizontalGroup(
            MorningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        MorningLayout.setVerticalGroup(
            MorningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        Afternoon.setBackground(new java.awt.Color(255, 219, 199));
        Afternoon.setMaximumSize(new java.awt.Dimension(12, 12));
        Afternoon.setMinimumSize(new java.awt.Dimension(12, 12));

        javax.swing.GroupLayout AfternoonLayout = new javax.swing.GroupLayout(Afternoon);
        Afternoon.setLayout(AfternoonLayout);
        AfternoonLayout.setHorizontalGroup(
            AfternoonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        AfternoonLayout.setVerticalGroup(
            AfternoonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        Both.setBackground(new java.awt.Color(127, 85, 57));
        Both.setMaximumSize(new java.awt.Dimension(12, 12));
        Both.setMinimumSize(new java.awt.Dimension(12, 12));

        javax.swing.GroupLayout BothLayout = new javax.swing.GroupLayout(Both);
        Both.setLayout(BothLayout);
        BothLayout.setHorizontalGroup(
            BothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        BothLayout.setVerticalGroup(
            BothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Day_PanelLayout = new javax.swing.GroupLayout(Day_Panel);
        Day_Panel.setLayout(Day_PanelLayout);
        Day_PanelLayout.setHorizontalGroup(
            Day_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Day_PanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Day_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Day_PanelLayout.createSequentialGroup()
                        .addComponent(Morning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Afternoon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Both, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Day_PanelLayout.setVerticalGroup(
            Day_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Day_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Day_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Morning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Afternoon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Both, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Day_Queue_Nav.setBackground(new java.awt.Color(255, 240, 244));

        Select_Day.setText("Select a day");

        Queue_color.setBackground(new java.awt.Color(255, 240, 244));
        Queue_color.setMaximumSize(new java.awt.Dimension(240, 34));
        Queue_color.setMinimumSize(new java.awt.Dimension(240, 34));
        Queue_color.setPreferredSize(new java.awt.Dimension(240, 34));

        Morning_color_queue.setBackground(new java.awt.Color(254, 176, 211));
        Morning_color_queue.setMaximumSize(new java.awt.Dimension(12, 12));
        Morning_color_queue.setMinimumSize(new java.awt.Dimension(12, 12));

        javax.swing.GroupLayout Morning_color_queueLayout = new javax.swing.GroupLayout(Morning_color_queue);
        Morning_color_queue.setLayout(Morning_color_queueLayout);
        Morning_color_queueLayout.setHorizontalGroup(
            Morning_color_queueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        Morning_color_queueLayout.setVerticalGroup(
            Morning_color_queueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        Afternoon_Queue.setText("Afternoon");

        Afternoon_color_queue.setBackground(new java.awt.Color(255, 219, 199));
        Afternoon_color_queue.setMaximumSize(new java.awt.Dimension(12, 12));
        Afternoon_color_queue.setMinimumSize(new java.awt.Dimension(12, 12));

        javax.swing.GroupLayout Afternoon_color_queueLayout = new javax.swing.GroupLayout(Afternoon_color_queue);
        Afternoon_color_queue.setLayout(Afternoon_color_queueLayout);
        Afternoon_color_queueLayout.setHorizontalGroup(
            Afternoon_color_queueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        Afternoon_color_queueLayout.setVerticalGroup(
            Afternoon_color_queueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        Morning_Queue.setText("Morning");

        Both_queue.setBackground(new java.awt.Color(127, 85, 57));
        Both_queue.setMaximumSize(new java.awt.Dimension(12, 12));
        Both_queue.setMinimumSize(new java.awt.Dimension(12, 12));

        javax.swing.GroupLayout Both_queueLayout = new javax.swing.GroupLayout(Both_queue);
        Both_queue.setLayout(Both_queueLayout);
        Both_queueLayout.setHorizontalGroup(
            Both_queueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        Both_queueLayout.setVerticalGroup(
            Both_queueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        Both_Sched_Queue.setText("Both");

        javax.swing.GroupLayout Queue_colorLayout = new javax.swing.GroupLayout(Queue_color);
        Queue_color.setLayout(Queue_colorLayout);
        Queue_colorLayout.setHorizontalGroup(
            Queue_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Queue_colorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Morning_color_queue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Morning_Queue)
                .addGap(15, 15, 15)
                .addComponent(Afternoon_color_queue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Afternoon_Queue)
                .addGap(20, 20, 20)
                .addComponent(Both_queue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Both_Sched_Queue)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        Queue_colorLayout.setVerticalGroup(
            Queue_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Queue_colorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Queue_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Both_Sched_Queue)
                    .addComponent(Morning_Queue)
                    .addComponent(Afternoon_Queue)
                    .addComponent(Morning_color_queue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Afternoon_color_queue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Both_queue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout Day_Queue_NavLayout = new javax.swing.GroupLayout(Day_Queue_Nav);
        Day_Queue_Nav.setLayout(Day_Queue_NavLayout);
        Day_Queue_NavLayout.setHorizontalGroup(
            Day_Queue_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Day_Queue_NavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Select_Day)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                .addComponent(Queue_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Day_Queue_NavLayout.setVerticalGroup(
            Day_Queue_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Day_Queue_NavLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Day_Queue_NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Queue_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Select_Day))
                .addContainerGap())
        );

        javax.swing.GroupLayout Selecting_DayLayout = new javax.swing.GroupLayout(Selecting_Day);
        Selecting_Day.setLayout(Selecting_DayLayout);
        Selecting_DayLayout.setHorizontalGroup(
            Selecting_DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Selecting_DayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Selecting_DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Selecting_DayLayout.createSequentialGroup()
                        .addComponent(Day_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Day_Queue_Nav, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Selecting_DayLayout.setVerticalGroup(
            Selecting_DayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Selecting_DayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Day_Queue_Nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Day_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Doctor_AvailLayout = new javax.swing.GroupLayout(Doctor_Avail);
        Doctor_Avail.setLayout(Doctor_AvailLayout);
        Doctor_AvailLayout.setHorizontalGroup(
            Doctor_AvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        Doctor_AvailLayout.setVerticalGroup(
            Doctor_AvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        Date_of_Appt.setBackground(new java.awt.Color(255, 219, 199));

        Day_of_Appt.setText("March 13");

        javax.swing.GroupLayout Date_of_ApptLayout = new javax.swing.GroupLayout(Date_of_Appt);
        Date_of_Appt.setLayout(Date_of_ApptLayout);
        Date_of_ApptLayout.setHorizontalGroup(
            Date_of_ApptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Date_of_ApptLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Day_of_Appt)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        Date_of_ApptLayout.setVerticalGroup(
            Date_of_ApptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Date_of_ApptLayout.createSequentialGroup()
                .addComponent(Day_of_Appt)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        Select_Doctor.setBackground(new java.awt.Color(255, 240, 244));

        Pick_Doctor.setText("Select a Doctor");

        javax.swing.GroupLayout Select_DoctorLayout = new javax.swing.GroupLayout(Select_Doctor);
        Select_Doctor.setLayout(Select_DoctorLayout);
        Select_DoctorLayout.setHorizontalGroup(
            Select_DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Select_DoctorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pick_Doctor)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        Select_DoctorLayout.setVerticalGroup(
            Select_DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Select_DoctorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pick_Doctor)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Doctor.setMaximumSize(new java.awt.Dimension(300, 54));
        Doctor.setMinimumSize(new java.awt.Dimension(300, 54));
        Doctor.setPreferredSize(new java.awt.Dimension(300, 54));

        Circle.setBackground(new java.awt.Color(0, 255, 204));
        Circle.setMaximumSize(new java.awt.Dimension(42, 42));
        Circle.setMinimumSize(new java.awt.Dimension(42, 42));
        Circle.setPreferredSize(new java.awt.Dimension(42, 42));

        javax.swing.GroupLayout CircleLayout = new javax.swing.GroupLayout(Circle);
        Circle.setLayout(CircleLayout);
        CircleLayout.setHorizontalGroup(
            CircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        CircleLayout.setVerticalGroup(
            CircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        Doctor_Role.setText("Family is Love");

        Doctor_Name.setText("Dr. Sheldon Cooper");

        javax.swing.GroupLayout DoctorLayout = new javax.swing.GroupLayout(Doctor);
        Doctor.setLayout(DoctorLayout);
        DoctorLayout.setHorizontalGroup(
            DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Circle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Doctor_Role)
                    .addComponent(Doctor_Name))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DoctorLayout.setVerticalGroup(
            DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DoctorLayout.createSequentialGroup()
                        .addComponent(Doctor_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_Role))
                    .addComponent(Circle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Day_ScrollBar.setBackground(new java.awt.Color(255, 240, 244));
        Day_ScrollBar.setOrientation(javax.swing.JScrollBar.HORIZONTAL);

        Doctor_ScrollBar.setBackground(new java.awt.Color(255, 240, 244));

        javax.swing.GroupLayout Select_Day_Doctor_PanelLayout = new javax.swing.GroupLayout(Select_Day_Doctor_Panel);
        Select_Day_Doctor_Panel.setLayout(Select_Day_Doctor_PanelLayout);
        Select_Day_Doctor_PanelLayout.setHorizontalGroup(
            Select_Day_Doctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Select_Day_Doctor_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Select_Day_Doctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Select_Day_Doctor_PanelLayout.createSequentialGroup()
                        .addComponent(Selecting_Day, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Select_Day_Doctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Select_Day_Doctor_PanelLayout.createSequentialGroup()
                                .addComponent(Select_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Date_of_Appt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Select_Day_Doctor_PanelLayout.createSequentialGroup()
                                .addComponent(Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Doctor_ScrollBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Doctor_Avail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Day_ScrollBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Select_Day_Doctor_PanelLayout.setVerticalGroup(
            Select_Day_Doctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Select_Day_Doctor_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Select_Day_Doctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Select_Day_Doctor_PanelLayout.createSequentialGroup()
                        .addComponent(Selecting_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Day_ScrollBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(7, Short.MAX_VALUE))
                    .addGroup(Select_Day_Doctor_PanelLayout.createSequentialGroup()
                        .addComponent(Doctor_Avail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Select_Day_Doctor_PanelLayout.createSequentialGroup()
                        .addGroup(Select_Day_Doctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Date_of_Appt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Select_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Select_Day_Doctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Select_Day_Doctor_PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Select_Day_Doctor_PanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Doctor_ScrollBar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        add(Select_Day_Doctor_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 1110, -1));

        Timezone.setBackground(new java.awt.Color(255, 240, 244));
        Timezone.setMaximumSize(new java.awt.Dimension(420, 400));
        Timezone.setMinimumSize(new java.awt.Dimension(420, 400));
        Timezone.setPreferredSize(new java.awt.Dimension(420, 400));

        Morning_Time.setMaximumSize(new java.awt.Dimension(180, 100));
        Morning_Time.setMinimumSize(new java.awt.Dimension(180, 100));
        Morning_Time.setPreferredSize(new java.awt.Dimension(180, 100));

        javax.swing.GroupLayout Morning_ImageLayout = new javax.swing.GroupLayout(Morning_Image);
        Morning_Image.setLayout(Morning_ImageLayout);
        Morning_ImageLayout.setHorizontalGroup(
            Morning_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        Morning_ImageLayout.setVerticalGroup(
            Morning_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        Morning_Label.setText("Morning");

        javax.swing.GroupLayout Morning_TimeLayout = new javax.swing.GroupLayout(Morning_Time);
        Morning_Time.setLayout(Morning_TimeLayout);
        Morning_TimeLayout.setHorizontalGroup(
            Morning_TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Morning_TimeLayout.createSequentialGroup()
                .addGroup(Morning_TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Morning_Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Morning_TimeLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(Morning_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Morning_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(60, 60, 60))
        );
        Morning_TimeLayout.setVerticalGroup(
            Morning_TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Morning_TimeLayout.createSequentialGroup()
                .addComponent(Morning_Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Morning_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(Morning_TimeLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(Morning_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Afternoon_Time.setMaximumSize(new java.awt.Dimension(180, 100));
        Afternoon_Time.setMinimumSize(new java.awt.Dimension(180, 100));
        Afternoon_Time.setPreferredSize(new java.awt.Dimension(180, 100));

        Afternoon_ToggleButton.setText("Afternoon");
        Afternoon_ToggleButton.setMaximumSize(new java.awt.Dimension(180, 100));
        Afternoon_ToggleButton.setMinimumSize(new java.awt.Dimension(180, 100));
        Afternoon_ToggleButton.setPreferredSize(new java.awt.Dimension(180, 100));
        Afternoon_ToggleButton.addActionListener(this::Afternoon_ToggleButtonActionPerformed);

        javax.swing.GroupLayout Afternoon_TimeLayout = new javax.swing.GroupLayout(Afternoon_Time);
        Afternoon_Time.setLayout(Afternoon_TimeLayout);
        Afternoon_TimeLayout.setHorizontalGroup(
            Afternoon_TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Afternoon_ToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Afternoon_TimeLayout.setVerticalGroup(
            Afternoon_TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Afternoon_ToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Select_Time.setText("Select a time of Day");

        Schedule_Note.setColumns(20);
        Schedule_Note.setRows(5);
        Schedule_Note.setText("Avail on the time that you are able to walk into the clinic. Failure to attend the appointment before the desired time ends will have the entire appointment be discarded,");
        jScrollPane1.setViewportView(Schedule_Note);

        javax.swing.GroupLayout TimezoneLayout = new javax.swing.GroupLayout(Timezone);
        Timezone.setLayout(TimezoneLayout);
        TimezoneLayout.setHorizontalGroup(
            TimezoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimezoneLayout.createSequentialGroup()
                .addGroup(TimezoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TimezoneLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(TimezoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Select_Time)
                            .addGroup(TimezoneLayout.createSequentialGroup()
                                .addComponent(Morning_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(Afternoon_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(TimezoneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        TimezoneLayout.setVerticalGroup(
            TimezoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimezoneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Select_Time)
                .addGap(29, 29, 29)
                .addGroup(TimezoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Morning_Time, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(Afternoon_Time, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        add(Timezone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 450, 370));

        Profile.setBackground(new java.awt.Color(255, 240, 244));

        Set_Acct.setBackground(new java.awt.Color(255, 240, 244));
        Set_Acct.setMaximumSize(new java.awt.Dimension(300, 238));
        Set_Acct.setMinimumSize(new java.awt.Dimension(300, 238));
        Set_Acct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        User_Profile_Inputs.setBackground(new java.awt.Color(255, 240, 244));
        User_Profile_Inputs.setLayout(new java.awt.GridBagLayout());

        User_FN.setText("First Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        User_Profile_Inputs.add(User_FN, gridBagConstraints);

        FN_Input.setBackground(new java.awt.Color(250, 234, 238));
        FN_Input.setText("Enter your First Name ");
        FN_Input.setMaximumSize(new java.awt.Dimension(50, 22));
        FN_Input.setMinimumSize(new java.awt.Dimension(50, 22));
        FN_Input.setPreferredSize(new java.awt.Dimension(50, 22));
        FN_Input.addActionListener(this::FN_InputActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        User_Profile_Inputs.add(FN_Input, gridBagConstraints);

        User_LN.setText("Last Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 5, 0);
        User_Profile_Inputs.add(User_LN, gridBagConstraints);

        LN_Input.setBackground(new java.awt.Color(250, 234, 238));
        LN_Input.setText("Enter your Last Name ");
        LN_Input.setMinimumSize(new java.awt.Dimension(50, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        User_Profile_Inputs.add(LN_Input, gridBagConstraints);

        User_Address.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 5, 0);
        User_Profile_Inputs.add(User_Address, gridBagConstraints);

        Address_Input.setBackground(new java.awt.Color(250, 234, 238));
        Address_Input.setText("Enter your Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        User_Profile_Inputs.add(Address_Input, gridBagConstraints);

        User_Contact.setText("Main Contact");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 5, 0);
        User_Profile_Inputs.add(User_Contact, gridBagConstraints);

        Contact_Input.setBackground(new java.awt.Color(250, 234, 238));
        Contact_Input.setText("Enter your Contact Details");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        User_Profile_Inputs.add(Contact_Input, gridBagConstraints);

        Set_Acct.add(User_Profile_Inputs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 330));

        Set_Profile.setBackground(new java.awt.Color(255, 240, 244));
        Set_Profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bilog.setBackground(new java.awt.Color(255, 255, 0));
        Bilog.setMaximumSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout BilogLayout = new javax.swing.GroupLayout(Bilog);
        Bilog.setLayout(BilogLayout);
        BilogLayout.setHorizontalGroup(
            BilogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        BilogLayout.setVerticalGroup(
            BilogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Set_Profile.add(Bilog, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 61, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 240, 244));

        Take_Photo.setText("Take a photo");
        Take_Photo.addActionListener(this::Take_PhotoActionPerformed);

        Photo_Icon.setBackground(new java.awt.Color(255, 0, 0));
        Photo_Icon.setMaximumSize(new java.awt.Dimension(20, 20));
        Photo_Icon.setMinimumSize(new java.awt.Dimension(20, 20));
        Photo_Icon.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout Photo_IconLayout = new javax.swing.GroupLayout(Photo_Icon);
        Photo_Icon.setLayout(Photo_IconLayout);
        Photo_IconLayout.setHorizontalGroup(
            Photo_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        Photo_IconLayout.setVerticalGroup(
            Photo_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(Photo_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Take_Photo)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Photo_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Take_Photo))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Set_Profile.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 78, -1, -1));

        jLabel5.setText("Setup your Profile");
        Set_Profile.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 27, -1, -1));

        Bday_Sex_Blood.setBackground(new java.awt.Color(255, 240, 244));
        Bday_Sex_Blood.setMaximumSize(new java.awt.Dimension(300, 100));
        Bday_Sex_Blood.setMinimumSize(new java.awt.Dimension(300, 100));
        Bday_Sex_Blood.setLayout(new java.awt.GridBagLayout());

        User_Bday.setText("Birthday");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        Bday_Sex_Blood.add(User_Bday, gridBagConstraints);

        Bday_TextField.setBackground(new java.awt.Color(250, 234, 238));
        Bday_TextField.setText("Insert your Birthday here");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 32, 50);
        Bday_Sex_Blood.add(Bday_TextField, gridBagConstraints);

        User_Sex.setText("Sex");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        Bday_Sex_Blood.add(User_Sex, gridBagConstraints);

        Sex_List.setBackground(new java.awt.Color(250, 234, 238));
        Sex_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        Sex_List.setSelectedItem(Male, Female);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        Bday_Sex_Blood.add(Sex_List, gridBagConstraints);

        User_BloodType.setText("Blood Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        Bday_Sex_Blood.add(User_BloodType, gridBagConstraints);

        BloodType_List.setBackground(new java.awt.Color(250, 234, 238));
        BloodType_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A Positive", "A Negative", "B Positive", "B Negative", "O Positive", "O Negative", "AB Positive", "AB Negative" }));
        BloodType_List.setSelectedItem(O Positive);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        Bday_Sex_Blood.add(BloodType_List, gridBagConstraints);

        Set_Profile.add(Bday_Sex_Blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 330, 150));

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Set_Profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Set_Acct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Set_Profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Set_Acct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 630, 370));

        Continue_Button.setBackground(new java.awt.Color(137, 74, 105));
        Continue_Button.setText("Continue");
        Continue_Button.addActionListener(this::Continue_ButtonActionPerformed);
        add(Continue_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 750, -1, -1));

        Cancel_button.setText("Cancel the setup");
        add(Cancel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 750, -1, -1));

        Back_button.setText("Back");
        Back_button.addActionListener(this::Back_buttonActionPerformed);
        add(Back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        javax.swing.GroupLayout Continue_Cancel_PanelLayout = new javax.swing.GroupLayout(Continue_Cancel_Panel);
        Continue_Cancel_Panel.setLayout(Continue_Cancel_PanelLayout);
        Continue_Cancel_PanelLayout.setHorizontalGroup(
            Continue_Cancel_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        Continue_Cancel_PanelLayout.setVerticalGroup(
            Continue_Cancel_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(Continue_Cancel_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 740, 260, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void Continue_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Continue_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Continue_ButtonActionPerformed

    private void Back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back_buttonActionPerformed

    private void Afternoon_ToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Afternoon_ToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Afternoon_ToggleButtonActionPerformed

    private void Take_PhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Take_PhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Take_PhotoActionPerformed

    private void FN_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FN_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FN_InputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address_Input;
    private javax.swing.JPanel Afternoon;
    private javax.swing.JLabel Afternoon_Queue;
    private javax.swing.JPanel Afternoon_Time;
    private javax.swing.JToggleButton Afternoon_ToggleButton;
    private javax.swing.JPanel Afternoon_color_queue;
    private javax.swing.JButton Back_button;
    private javax.swing.JPanel Bday_Sex_Blood;
    private javax.swing.JTextField Bday_TextField;
    private javax.swing.JPanel Bilog;
    private javax.swing.JComboBox<String> BloodType_List;
    private javax.swing.JPanel Both;
    private javax.swing.JLabel Both_Sched_Queue;
    private javax.swing.JPanel Both_queue;
    private javax.swing.JButton Cancel_button;
    private javax.swing.JPanel Circle;
    private javax.swing.JTextField Contact_Input;
    private javax.swing.JButton Continue_Button;
    private javax.swing.JPanel Continue_Cancel_Panel;
    private javax.swing.JPanel Date;
    private javax.swing.JPanel Date_of_Appt;
    private javax.swing.JLabel Day;
    private javax.swing.JPanel Day_Number;
    private javax.swing.JPanel Day_Panel;
    private javax.swing.JPanel Day_Queue_Nav;
    private javax.swing.JScrollBar Day_ScrollBar;
    private javax.swing.JLabel Day_of_Appt;
    private javax.swing.JPanel Doctor;
    private javax.swing.JPanel Doctor_Avail;
    private javax.swing.JLabel Doctor_Name;
    private javax.swing.JLabel Doctor_Role;
    private javax.swing.JScrollBar Doctor_ScrollBar;
    private javax.swing.JTextField FN_Input;
    private javax.swing.JTextField LN_Input;
    private javax.swing.JLabel Month;
    private javax.swing.JPanel Morning;
    private javax.swing.JPanel Morning_Image;
    private javax.swing.JLabel Morning_Label;
    private javax.swing.JLabel Morning_Queue;
    private javax.swing.JPanel Morning_Time;
    private javax.swing.JToggleButton Morning_button;
    private javax.swing.JPanel Morning_color_queue;
    private javax.swing.JPanel Navigator;
    private javax.swing.JPanel Photo_Icon;
    private javax.swing.JLabel Pick_Doctor;
    private javax.swing.JPanel Profile;
    private javax.swing.JProgressBar ProgBar4;
    private javax.swing.JProgressBar ProgBar5;
    private javax.swing.JProgressBar ProgBar6;
    private javax.swing.JPanel Queue_color;
    private javax.swing.JTextArea Schedule_Note;
    private javax.swing.JLabel Select_Day;
    private javax.swing.JPanel Select_Day_Doctor_Panel;
    private javax.swing.JPanel Select_Doctor;
    private javax.swing.JLabel Select_Time;
    private javax.swing.JPanel Selecting_Day;
    private javax.swing.JPanel Set_Acct;
    private javax.swing.JPanel Set_Profile;
    private javax.swing.JComboBox<String> Sex_List;
    private javax.swing.JButton Take_Photo;
    private javax.swing.JPanel Timezone;
    private javax.swing.JLabel User_Address;
    private javax.swing.JLabel User_Bday;
    private javax.swing.JLabel User_BloodType;
    private javax.swing.JLabel User_Contact;
    private javax.swing.JLabel User_FN;
    private javax.swing.JLabel User_LN;
    private javax.swing.JPanel User_Profile_Inputs;
    private javax.swing.JLabel User_Sex;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
