/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui;

/**
 *
 * @author Lei
 */
public class New_Acct_Login extends javax.swing.JPanel {

    /**
     * Creates new form ExistingAcctLogin
     */
    public New_Acct_Login() {
        initComponents();
        Styling();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Existing_Login_Panel = new javax.swing.JPanel();
        Login_Button = new javax.swing.JButton();
        Existing_Email = new javax.swing.JLabel();
        Existing_PIN = new javax.swing.JLabel();
        Username_Field = new javax.swing.JTextField();
        PIN_Pass = new javax.swing.JPasswordField();
        Existing_PIN1 = new javax.swing.JLabel();
        PIN_Pass1 = new javax.swing.JPasswordField();
        Note = new javax.swing.JLabel();
        Backdrop = new javax.swing.JPanel();
        Navigator = new javax.swing.JPanel();
        ProgBar1 = new javax.swing.JProgressBar();
        ProgBar2 = new javax.swing.JProgressBar();
        ProgBar3 = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(255, 248, 248));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Existing_Login_Panel.setBackground(new java.awt.Color(250, 234, 238));
        Existing_Login_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Existing_Login_Panel.setPreferredSize(new java.awt.Dimension(550, 450));

        Login_Button.setBackground(new java.awt.Color(137, 74, 105));
        Login_Button.setText("Proceed");
        Login_Button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Login_Button.setPreferredSize(new java.awt.Dimension(350, 23));
        Login_Button.addActionListener(this::Login_ButtonActionPerformed);

        Existing_Email.setText("Email or Phone Number");

        Existing_PIN.setText("Confirm PIN");

        Username_Field.setText("Email / Phone Number");

        PIN_Pass.setText("jPasswordField1");

        Existing_PIN1.setText("Create PIN");

        PIN_Pass1.setText("jPasswordField1");

        Note.setText("This will serve as your main contact");

        javax.swing.GroupLayout Existing_Login_PanelLayout = new javax.swing.GroupLayout(Existing_Login_Panel);
        Existing_Login_Panel.setLayout(Existing_Login_PanelLayout);
        Existing_Login_PanelLayout.setHorizontalGroup(
            Existing_Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Existing_Login_PanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(Existing_Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Existing_Login_PanelLayout.createSequentialGroup()
                        .addGroup(Existing_Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Existing_Email)
                            .addComponent(Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(98, Short.MAX_VALUE))
                    .addGroup(Existing_Login_PanelLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(Existing_Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PIN_Pass, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(Existing_PIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(Existing_Login_PanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(Note)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Existing_Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Existing_Login_PanelLayout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(Existing_PIN1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(319, Short.MAX_VALUE)))
            .addGroup(Existing_Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Existing_Login_PanelLayout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(PIN_Pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(318, Short.MAX_VALUE)))
        );
        Existing_Login_PanelLayout.setVerticalGroup(
            Existing_Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Existing_Login_PanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Existing_Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Note)
                .addGap(18, 18, 18)
                .addComponent(Existing_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PIN_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(Existing_Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Existing_Login_PanelLayout.createSequentialGroup()
                    .addGap(165, 165, 165)
                    .addComponent(Existing_PIN1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(233, Short.MAX_VALUE)))
            .addGroup(Existing_Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Existing_Login_PanelLayout.createSequentialGroup()
                    .addContainerGap(221, Short.MAX_VALUE)
                    .addComponent(PIN_Pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(172, 172, 172)))
        );

        add(Existing_Login_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 549, -1));

        Backdrop.setPreferredSize(new java.awt.Dimension(450, 800));
        Backdrop.setLayout(new java.awt.BorderLayout());
        add(Backdrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Navigator.setBackground(new java.awt.Color(255, 248, 248));
        Navigator.setMaximumSize(new java.awt.Dimension(720, 10));
        Navigator.setMinimumSize(new java.awt.Dimension(720, 10));
        Navigator.setPreferredSize(new java.awt.Dimension(720, 10));
        Navigator.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        ProgBar1.setBackground(new java.awt.Color(229, 214, 218));
        ProgBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar1.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar1);

        ProgBar2.setBackground(new java.awt.Color(127, 85, 57));
        ProgBar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar2.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar2);

        ProgBar3.setBackground(new java.awt.Color(229, 214, 218));
        ProgBar3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar3.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar3);

        add(Navigator, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 720, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backdrop;
    private javax.swing.JLabel Existing_Email;
    private javax.swing.JPanel Existing_Login_Panel;
    private javax.swing.JLabel Existing_PIN;
    private javax.swing.JLabel Existing_PIN1;
    private javax.swing.JButton Login_Button;
    private javax.swing.JPanel Navigator;
    private javax.swing.JLabel Note;
    private javax.swing.JPasswordField PIN_Pass;
    private javax.swing.JPasswordField PIN_Pass1;
    private javax.swing.JProgressBar ProgBar1;
    private javax.swing.JProgressBar ProgBar2;
    private javax.swing.JProgressBar ProgBar3;
    private javax.swing.JTextField Username_Field;
    // End of variables declaration//GEN-END:variables
    private void Styling() {
        // 1. Define Fonts
        java.awt.Font manropeBold = new java.awt.Font("Manrope", java.awt.Font.BOLD, 16);
        java.awt.Font manropeMediumSmall = new java.awt.Font("Manrope", java.awt.Font.PLAIN, 10); 

        // 2. Apply Label Styling
        Existing_Email.setFont(manropeBold);
        Existing_Email.setForeground(java.awt.Color.BLACK);
        
        Existing_PIN.setFont(manropeBold);
        Existing_PIN.setForeground(java.awt.Color.BLACK);
        
        Existing_PIN1.setFont(manropeBold);
        Existing_PIN1.setForeground(java.awt.Color.BLACK);
        
        Note.setFont(manropeMediumSmall);
        Note.setForeground(java.awt.Color.BLACK);

        // 3. THE PROCEED BUTTON (71px Radius + White Text)
        Login_Button.setContentAreaFilled(false);
        Login_Button.setFocusPainted(false);
        Login_Button.setOpaque(false);
        Login_Button.setBorder(new javax.swing.border.AbstractBorder() {
            @Override
            public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                
                g2.setColor(new java.awt.Color(137, 74, 105));
                g2.fillRoundRect(x, y, width - 1, height - 1, 71, 71);
                
                g2.setColor(java.awt.Color.WHITE);
                g2.setFont(manropeBold);
                java.awt.FontMetrics fm = g2.getFontMetrics();
                String text = "Proceed";
                int textX = (width - fm.stringWidth(text)) / 2;
                int textY = (height - fm.getHeight()) / 2 + fm.getAscent();
                g2.drawString(text, textX, textY);
                
                g2.dispose();
            }
        });

        Existing_Login_Panel.setOpaque(false);
        Existing_Login_Panel.setBorder(new javax.swing.border.AbstractBorder() {
            @Override
            public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                
                java.awt.Color bgColor = new java.awt.Color(250, 234, 238);
                g2.setColor(bgColor);
                
                g2.fillRoundRect(x, y, width - 1, height - 1, 28, 28);
                g2.drawRoundRect(x, y, width - 1, height - 1, 28, 28);
                
                g2.dispose();
            }
        });
    }}