/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.one.patientmanagement.ui;

/**
 *
 * @author Lei
 */
public class New_Acct_Appointment extends javax.swing.JPanel {

    /**
     * Creates new form New_Acct_Appointment
     */
    public New_Acct_Appointment() {
        initComponents();
        Styling();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Navigator = new javax.swing.JPanel();
        ProgBar4 = new javax.swing.JProgressBar();
        ProgBar5 = new javax.swing.JProgressBar();
        ProgBar6 = new javax.swing.JProgressBar();
        Select_Service = new javax.swing.JLabel();
        Service_Panel = new javax.swing.JPanel();
        General_Button = new javax.swing.JButton();
        Pedia_Button = new javax.swing.JButton();
        Counseling_Button = new javax.swing.JButton();
        Phy_Med_Exam_Button = new javax.swing.JButton();
        Cancel_Continue_Button = new javax.swing.JPanel();
        Cancel_Button = new javax.swing.JButton();
        Continue_button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 248, 248));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Navigator.setBackground(new java.awt.Color(255, 248, 248));
        Navigator.setMaximumSize(new java.awt.Dimension(720, 10));
        Navigator.setMinimumSize(new java.awt.Dimension(720, 10));
        Navigator.setPreferredSize(new java.awt.Dimension(720, 10));
        Navigator.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        ProgBar4.setBackground(new java.awt.Color(229, 214, 218));
        ProgBar4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar4.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar4);

        ProgBar5.setBackground(new java.awt.Color(229, 214, 218));
        ProgBar5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar5.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar5);

        ProgBar6.setBackground(new java.awt.Color(127, 85, 57));
        ProgBar6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ProgBar6.setPreferredSize(new java.awt.Dimension(220, 10));
        Navigator.add(ProgBar6);

        add(Navigator, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 720, 20));

        Select_Service.setText("Select a service");
        add(Select_Service, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 450, -1));

        Service_Panel.setOpaque(false);
        Service_Panel.setPreferredSize(new java.awt.Dimension(280, 350));
        Service_Panel.setLayout(new java.awt.GridLayout(4, 0));

        General_Button.setBackground(new java.awt.Color(114, 87, 98));
        General_Button.setText("General Checkup");
        General_Button.setPreferredSize(new java.awt.Dimension(530, 65));
        Service_Panel.add(General_Button);

        Pedia_Button.setBackground(new java.awt.Color(250, 234, 238));
        Pedia_Button.setText("Pediatrics");
        Pedia_Button.setPreferredSize(new java.awt.Dimension(530, 65));
        Service_Panel.add(Pedia_Button);

        Counseling_Button.setBackground(new java.awt.Color(250, 234, 238));
        Counseling_Button.setText("Counseling");
        Counseling_Button.setPreferredSize(new java.awt.Dimension(530, 65));
        Counseling_Button.addActionListener(this::Counseling_ButtonActionPerformed);
        Service_Panel.add(Counseling_Button);

        Phy_Med_Exam_Button.setBackground(new java.awt.Color(250, 234, 238));
        Phy_Med_Exam_Button.setText("Physical / Medical Examination");
        Phy_Med_Exam_Button.setPreferredSize(new java.awt.Dimension(530, 65));
        Service_Panel.add(Phy_Med_Exam_Button);

        add(Service_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 450, 240));

        Cancel_Continue_Button.setLayout(new java.awt.GridBagLayout());

        Cancel_Button.setText("Cancel the setup");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 164, 17, 0);
        Cancel_Continue_Button.add(Cancel_Button, gridBagConstraints);

        Continue_button.setBackground(new java.awt.Color(137, 74, 105));
        Continue_button.setText("Continue");
        Continue_button.setMaximumSize(new java.awt.Dimension(390, 50));
        Continue_button.setMinimumSize(new java.awt.Dimension(390, 50));
        Continue_button.setPreferredSize(new java.awt.Dimension(390, 50));
        Continue_button.addActionListener(this::Continue_buttonActionPerformed);
        Cancel_Continue_Button.add(Continue_button, new java.awt.GridBagConstraints());

        add(Cancel_Continue_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 460, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void Counseling_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Counseling_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Counseling_ButtonActionPerformed

    private void Continue_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Continue_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Continue_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_Button;
    private javax.swing.JPanel Cancel_Continue_Button;
    private javax.swing.JButton Continue_button;
    private javax.swing.JButton Counseling_Button;
    private javax.swing.JButton General_Button;
    private javax.swing.JPanel Navigator;
    private javax.swing.JButton Pedia_Button;
    private javax.swing.JButton Phy_Med_Exam_Button;
    private javax.swing.JProgressBar ProgBar4;
    private javax.swing.JProgressBar ProgBar5;
    private javax.swing.JProgressBar ProgBar6;
    private javax.swing.JLabel Select_Service;
    private javax.swing.JPanel Service_Panel;
    // End of variables declaration//GEN-END:variables

private void Styling() {
    // 1. DIMENSIONS & FONTS
    int totalWidth = 1200;
    java.awt.Dimension serviceBtnSize = new java.awt.Dimension(430, 65);
    
    java.awt.Font poppinsLarge = new java.awt.Font("Poppins", java.awt.Font.PLAIN, 28); 
    java.awt.Font manropeSemiBold16 = new java.awt.Font("Manrope", java.awt.Font.BOLD, 16);
    java.awt.Font manropeSubtitle = new java.awt.Font("Manrope", java.awt.Font.PLAIN, 18);
    
    java.awt.Color normalColor = new java.awt.Color(250, 234, 238);
    java.awt.Color activeColor = new java.awt.Color(114, 87, 98);

    // 2. COMPONENT STYLING (Fonts, Colors, Borders)
    Select_Service.setFont(poppinsLarge);
    Select_Service.setForeground(java.awt.Color.BLACK);
    Select_Service.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    javax.swing.JButton[] serviceButtons = {General_Button, Pedia_Button, Counseling_Button, Phy_Med_Exam_Button};
    for (javax.swing.JButton btn : serviceButtons) {
        btn.setPreferredSize(serviceBtnSize);
        btn.setFont(manropeSubtitle);
        btn.setFocusPainted(false);
        btn.setContentAreaFilled(false);
        btn.setBorder(new javax.swing.border.AbstractBorder() {
            @Override
            public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(c == General_Button ? activeColor : normalColor);
                int arc = 40; 
                if (c == General_Button) {
                    g2.fillRoundRect(x, y, width, height, arc, arc);
                    g2.fillRect(x, y + (height / 2), width, height / 2); 
                } else if (c == Phy_Med_Exam_Button) {
                    g2.fillRoundRect(x, y, width, height, arc, arc);
                    g2.fillRect(x, y, width, height / 2); 
                } else {
                    g2.fillRect(x, y, width, height);
                }
                g2.setColor(c == General_Button ? java.awt.Color.WHITE : java.awt.Color.BLACK);
                java.awt.FontMetrics fm = g2.getFontMetrics();
                String text = ((javax.swing.JButton)c).getText();
                g2.drawString(text, (width - fm.stringWidth(text)) / 2, (height - fm.getHeight()) / 2 + fm.getAscent());
                g2.dispose();
            }
        });
    }

    // Continue Button Styling
    Continue_button.setContentAreaFilled(false);
    Continue_button.setBorder(new javax.swing.border.AbstractBorder() {
        @Override
        public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(new java.awt.Color(137, 74, 105));
            g2.fillRoundRect(x, y, width, height, 71, 71);
            g2.setColor(java.awt.Color.WHITE);
            g2.setFont(manropeSemiBold16);
            java.awt.FontMetrics fm = g2.getFontMetrics();
            g2.drawString("Continue", (width - fm.stringWidth("Continue")) / 2, (height - fm.getHeight()) / 2 + fm.getAscent());
            g2.dispose();
        }
    });

    Cancel_Button.setFont(manropeSemiBold16);
    Cancel_Button.setContentAreaFilled(false);
    Cancel_Button.setBorderPainted(false);

    // 3. INTERNAL PANEL LAYOUTS
    Service_Panel.setLayout(new java.awt.GridBagLayout());
    java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
    gbc.gridx = 0; gbc.insets = new java.awt.Insets(10, 0, 10, 0); 
    Service_Panel.removeAll();
    Service_Panel.add(General_Button, gbc); Service_Panel.add(Pedia_Button, gbc);
    Service_Panel.add(Counseling_Button, gbc); Service_Panel.add(Phy_Med_Exam_Button, gbc);

    // Update Cancel_Continue_Button to stack Continue on top of Cancel
    Cancel_Continue_Button.setOpaque(false);
    Cancel_Continue_Button.setLayout(new java.awt.GridBagLayout());
    Cancel_Continue_Button.removeAll();
    java.awt.GridBagConstraints cbc = new java.awt.GridBagConstraints();
    cbc.gridx = 0; cbc.gridy = 0;
    Cancel_Continue_Button.add(Continue_button, cbc);
    cbc.gridy = 1; cbc.insets = new java.awt.Insets(20, 0, 0, 0); // Gap between Continue and Cancel
    Cancel_Continue_Button.add(Cancel_Button, cbc);

    // 4. THE 1200px CENTERED VERTICAL STACK
    // Navigation ends at Y=30. Gap of 200px means start at Y=230.
    int startY = 100; 
    int labelHeight = 40;
    int servicePanelHeight = 360; 
    int panelGap = 20; // Gap between Label and Service Panel
    int footerGap = 60; // Gap between Service Panel and footer buttons

    // Positioning
    add(Select_Service, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, startY, 1200, labelHeight));
    
    int servicePanelY = startY + labelHeight + panelGap; // 230 + 40 + 30 = 300
    add(Service_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints((totalWidth - 430) / 2, servicePanelY, 430, servicePanelHeight));
    
    int footerY = servicePanelY + servicePanelHeight + footerGap; // 300 + 360 + 100 = 760
    add(Cancel_Continue_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints((totalWidth - 460) / 2, footerY, 460, 150));

    revalidate();
    repaint();
}

}